# Generated by Django 3.2 on 2021-11-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('message', models.TextField(max_length=300)),
            ],
            options={
                'ordering': ('-date_sent',),
            },
        ),
    ]
